/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_logo = new javax.swing.JLabel();
        about_details = new javax.swing.JTextArea();
        about_title = new javax.swing.JLabel();
        white_bg_small = new javax.swing.JLabel();
        menu_stat_mem = new javax.swing.JLabel();
        menu_stat_mem1 = new javax.swing.JLabel();
        menu_stat_mem2 = new javax.swing.JLabel();
        menu_stat_work = new javax.swing.JLabel();
        menu_stat_work1 = new javax.swing.JLabel();
        menu_stat_work2 = new javax.swing.JLabel();
        menu_stat_diet = new javax.swing.JLabel();
        menu_stat_diet1 = new javax.swing.JLabel();
        menu_stat_diet2 = new javax.swing.JLabel();
        menu_stat_routine = new javax.swing.JLabel();
        menu_stat_routine1 = new javax.swing.JLabel();
        menu_stat_routine2 = new javax.swing.JLabel();
        stats_title = new javax.swing.JLabel();
        white_bg = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1020, 530));
        setLayout(null);

        menu_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menu_logo.png"))); // NOI18N
        add(menu_logo);
        menu_logo.setBounds(80, 30, 150, 150);

        about_details.setEditable(false);
        about_details.setColumns(20);
        about_details.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        about_details.setLineWrap(true);
        about_details.setRows(5);
        about_details.setText("Vall Gym, Tacloban City's pre- miere fitness destination, de- dicated to transforming lives through fitness excellence.\n\nOur state-of-the-art facility, di- verse equipment, and passion- ate trainers cater to all levels, fostering a supportive commu- nity committed to your health and wellness journey. Join us and experience the Vall Gym difference today!");
        about_details.setWrapStyleWord(true);
        add(about_details);
        about_details.setBounds(50, 220, 230, 270);

        about_title.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
        about_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about_title.setText("About Us");
        add(about_title);
        about_title.setBounds(80, 160, 160, 60);

        white_bg_small.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        white_bg_small.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/white_bg_small.png"))); // NOI18N
        white_bg_small.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(white_bg_small);
        white_bg_small.setBounds(0, 0, 320, 530);

        menu_stat_mem.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        menu_stat_mem.setForeground(new java.awt.Color(255, 255, 255));
        menu_stat_mem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_stat_mem.setText("0");
        add(menu_stat_mem);
        menu_stat_mem.setBounds(450, 170, 120, 60);

        menu_stat_mem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_stat_mem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/stats_bg.png"))); // NOI18N
        add(menu_stat_mem1);
        menu_stat_mem1.setBounds(440, 160, 140, 80);

        menu_stat_mem2.setFont(new java.awt.Font("Montserrat Medium", 0, 28)); // NOI18N
        menu_stat_mem2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_stat_mem2.setText("Total Gym Members");
        add(menu_stat_mem2);
        menu_stat_mem2.setBounds(590, 170, 320, 60);

        menu_stat_work.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        menu_stat_work.setForeground(new java.awt.Color(102, 102, 102));
        menu_stat_work.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_stat_work.setText("0");
        add(menu_stat_work);
        menu_stat_work.setBounds(480, 250, 90, 50);

        menu_stat_work1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_stat_work1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/stats_bg_small.png"))); // NOI18N
        add(menu_stat_work1);
        menu_stat_work1.setBounds(470, 250, 110, 50);

        menu_stat_work2.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        menu_stat_work2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_stat_work2.setText("Types of workouts offered");
        add(menu_stat_work2);
        menu_stat_work2.setBounds(590, 250, 330, 50);

        menu_stat_diet.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        menu_stat_diet.setForeground(new java.awt.Color(102, 102, 102));
        menu_stat_diet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_stat_diet.setText("0");
        add(menu_stat_diet);
        menu_stat_diet.setBounds(480, 310, 90, 50);

        menu_stat_diet1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_stat_diet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/stats_bg_small.png"))); // NOI18N
        add(menu_stat_diet1);
        menu_stat_diet1.setBounds(470, 310, 110, 50);

        menu_stat_diet2.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        menu_stat_diet2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_stat_diet2.setText("Types of diets offered");
        add(menu_stat_diet2);
        menu_stat_diet2.setBounds(590, 310, 330, 50);

        menu_stat_routine.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        menu_stat_routine.setForeground(new java.awt.Color(102, 102, 102));
        menu_stat_routine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_stat_routine.setText("0");
        add(menu_stat_routine);
        menu_stat_routine.setBounds(480, 370, 90, 50);

        menu_stat_routine1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_stat_routine1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/stats_bg_small.png"))); // NOI18N
        add(menu_stat_routine1);
        menu_stat_routine1.setBounds(470, 370, 110, 50);

        menu_stat_routine2.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        menu_stat_routine2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menu_stat_routine2.setText("Types of routines offered");
        add(menu_stat_routine2);
        menu_stat_routine2.setBounds(590, 370, 330, 50);

        stats_title.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
        stats_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stats_title.setText("Vall Gym Statistics");
        add(stats_title);
        stats_title.setBounds(520, 60, 320, 60);

        white_bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        white_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/white_bg.png"))); // NOI18N
        white_bg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(white_bg);
        white_bg.setBounds(330, 0, 690, 530);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea about_details;
    private javax.swing.JLabel about_title;
    private javax.swing.JLabel menu_logo;
    public javax.swing.JLabel menu_stat_diet;
    private javax.swing.JLabel menu_stat_diet1;
    private javax.swing.JLabel menu_stat_diet2;
    public javax.swing.JLabel menu_stat_mem;
    private javax.swing.JLabel menu_stat_mem1;
    private javax.swing.JLabel menu_stat_mem2;
    public javax.swing.JLabel menu_stat_routine;
    private javax.swing.JLabel menu_stat_routine1;
    private javax.swing.JLabel menu_stat_routine2;
    public javax.swing.JLabel menu_stat_work;
    private javax.swing.JLabel menu_stat_work1;
    private javax.swing.JLabel menu_stat_work2;
    private javax.swing.JLabel stats_title;
    private javax.swing.JLabel white_bg;
    private javax.swing.JLabel white_bg_small;
    // End of variables declaration//GEN-END:variables
}
